wp:
  port:
    client:
      server-url: ws://127.0.0.1:8080/wp
      port-forwarding-list:
        - remote-address: 127.0.0.1
          remote-port: 22
          bind-addr: 127.0.0.1
          bind-port: 8226
        - remote-address: 127.0.0.1
          remote-port: 21
          bind-addr: 127.0.0.1
          bind-port: 8227
logging:
  level:
    com.snail.core.handler.DataHandler: trace
