wp:
  port:
    client:
      remote-address: 127.0.0.1
      remote-port: 22
      server-url: ws://127.0.0.1:8080/wp
      bind-addr: 127.0.0.1
      bind-port: 8226
logging:
  level:
    com.snail.core.handler.DataHandler: trace
